DATASET:
    train_list: ['Human36M', 'COCO', 'MuCo']
    test_list: ['PW3D']
    input_joint_set: 'coco'
    target_joint_set: 'coco'
    workers: 64
    use_gt_input: False

MODEL:
    name: 'PAM'
    input_shape: [384, 288]

TRAIN:
    print_freq: 80
    batch_size: 1024
    shuffle: True
    begin_epoch: 1
    end_epoch: 180
    scheduler: 'step'
    lr: 0.0008
    lr_step: [10, 30, 60, 90, 120, 140]
    lr_factor: 0.9
    optimizer: 'adamw'

AUG:
    flip: True
    rotate_factor: 0

TEST:
    batch_size: 64
    shuffle: False